##################### Level Adapter #########################
from .conversable_agent import MyConversableAgent
from src.KnowledgeGraphs.math_graph import KnowledgeGraph
from src.KnowledgeGraphs.math_taxonomy import subsubsub_topics as mt_topics

class LevelAdapterAgent(MyConversableAgent):
    description = """
            LevelAdapterAgent is a smart and intuitive agent responsible for monitoring and adjusting the difficulty level of questions based on the user's performance. 
            By analyzing responses and determining the appropriate challenge level, LevelAdapterAgent ensures that the questions generated are neither too easy 
                nor too difficult, providing an optimal learning experience. 
            LevelAdapterAgent collaborates with ProblemGeneratorAgent to dynamically adapt the complexity of questions to match the StudentAgent's skill level.    
            """
    
    system_message = """
            You are LevelAdapterAgent, an agent responsible for determining when to adjust the difficulty level of questions generated by ProblemGeneratorAgent. 
            Monitor the StudentAgent's performance and analyze their responses to assess their skill level. 
            When necessary, instruct ProblemGeneratorAgent to increase or decrease the difficulty of questions to ensure they are appropriately challenging. 
            Your goal is to provide a balanced and adaptive learning experience, helping the StudentAgent to progressively improve without becoming frustrated or bored.
            """
    def __init__(self, **kwargs):
        super().__init__(
            name="LevelAdapterAgent",
            system_message=self.system_message,
            description=self.description,
            human_input_mode="NEVER",
            **kwargs
        )
        self.knowledge_graph = KnowledgeGraph()
        self.knowledge_graph.build_dag_from_dict(mt_topics)

    def adjust_difficulty(self, current_topic, performance):
        """Adjust the topic based on performance and knowledge graph structure."""
        if performance == 'good':
            next_topics = self.knowledge_graph.get_next_topics(current_topic)
            return next_topics[0] if next_topics else current_topic
        return self.knowledge_graph.get_prerequisites(current_topic)[-1]  # Move to the last prerequisite if performance is poor
