##################### Level Adapter #########################
from .conversable_agent import MyConversableAgent

class LevelAdapterAgent(MyConversableAgent):
    description = """
            LevelAdapterAgent is a smart and intuitive agent responsible for monitoring and adjusting the difficulty level of questions based on the user's performance. 
            By analyzing responses and determining the appropriate challenge level, LevelAdapterAgent ensures that the questions generated are neither too easy 
                nor too difficult, providing an optimal learning experience. 
            LevelAdapterAgent collaborates with ProblemGeneratorAgent to dynamically adapt the complexity of questions to match the StudentAgent's skill level.    
            """
    
    system_message = """
            You are LevelAdapterAgent, an agent responsible for determining when to adjust the difficulty level of questions generated by ProblemGeneratorAgent. 
            Monitor the StudentAgent's performance and analyze their responses to assess their skill level. 
            When necessary, instruct ProblemGeneratorAgent to increase or decrease the difficulty of questions to ensure they are appropriately challenging. 
            Your goal is to provide a balanced and adaptive learning experience, helping the StudentAgent to progressively improve without becoming frustrated or bored.
            """
    def __init__(self, **kwargs):
        super().__init__(
            name="LevelAdapterAgent",
            system_message=self.system_message,
            description=self.description,
            human_input_mode="NEVER",
            **kwargs
        )
        self.current_difficulty = 'easy'  # Default starting difficulty

    # Method to receive performance updates from LearnerModelAgent
    def update_from_learner_model(self, recommended_difficulty):
        """
        Update the difficulty level based on the recommendation from LearnerModelAgent.
        """
        if recommended_difficulty != self.current_difficulty:
            self.adjust_difficulty(recommended_difficulty)

    # Method to adjust the difficulty level
    def adjust_difficulty(self, new_difficulty):
        """
        Adjust the difficulty level of the questions generated by ProblemGeneratorAgent.
        """
        self.current_difficulty = new_difficulty
        self.inform_problem_generator(new_difficulty)

    # Method to communicate with ProblemGeneratorAgent
    def inform_problem_generator(self, new_difficulty):
        """
        Send a message to ProblemGeneratorAgent to adjust the question difficulty.
        """
        # Assuming there's a method in ProblemGeneratorAgent to handle this
        # This is a placeholder for communication logic
        print(f"Requesting ProblemGeneratorAgent to adjust difficulty to {new_difficulty}")
